# 参数管理

In [1]:
import torch
from torch import nn

In [2]:
net = nn.Sequential(
    nn.Linear(4, 8),
    nn.ReLU(),
    nn.Linear(8, 1)
)

In [3]:
X = torch.rand(size=(2, 4))

In [4]:
net(X)

tensor([[-0.2895],
        [-0.2992]], grad_fn=<AddmmBackward0>)

## 1. 参数访问

In [5]:
net[2].state_dict()

OrderedDict([('weight',
              tensor([[ 0.1471, -0.1398, -0.3485,  0.2786,  0.3036, -0.0711,  0.1713,  0.1301]])),
             ('bias', tensor([-0.3188]))])

In [9]:
net[2].bias.data

tensor([-0.3188])

In [10]:
net[2].weight

Parameter containing:
tensor([[ 0.1471, -0.1398, -0.3485,  0.2786,  0.3036, -0.0711,  0.1713,  0.1301]],
       requires_grad=True)

In [12]:
print(net[2].weight.grad)

None


## 2. 一次性访问所有参数

In [14]:
print(*[(name, param.shape) for name, param in  net.named_parameters()])

('0.weight', torch.Size([8, 4])) ('0.bias', torch.Size([8])) ('2.weight', torch.Size([1, 8])) ('2.bias', torch.Size([1]))


## 内置初始化

In [18]:
def init_normal(m):
    if type(m) == nn.Linear:
        nn.init.normal_(m.weight, mean=0, std=0.01)
        nn.init.zeros_(m.bias)  

net.apply(init_normal)

Sequential(
  (0): Linear(in_features=4, out_features=8, bias=True)
  (1): ReLU()
  (2): Linear(in_features=8, out_features=1, bias=True)
)

In [20]:
for layer in net:
    print(layer)

Linear(in_features=4, out_features=8, bias=True)
ReLU()
Linear(in_features=8, out_features=1, bias=True)
