# 自定义层

In [2]:
import torch
import torch.nn.functional as F
from torch import nn

In [3]:
class Centeredlayer(nn.Module):

    def __init__(self):
        super().__init__()
    
    def forward(self, x):
        return x - x.mean()

In [4]:
layer = Centeredlayer()
layer(torch.FloatTensor([i for i in range(10)]))

tensor([-4.5000, -3.5000, -2.5000, -1.5000, -0.5000,  0.5000,  1.5000,  2.5000,
         3.5000,  4.5000])

## 带参数的图层

In [5]:
class MyLinear_ReLU(nn.Module):

    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units, ))
    
    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data

        return F.relu(linear)

In [6]:
dense = MyLinear_ReLU(5, 3)
dense.weight

Parameter containing:
tensor([[ 1.7566, -0.7817,  1.0077],
        [ 0.6651,  1.4834,  0.9624],
        [-0.4136,  1.8435,  0.1910],
        [-0.3778,  0.1778,  0.6610],
        [ 0.5092,  0.0289,  0.4458]], requires_grad=True)

In [7]:
net = nn.Sequential(
    MyLinear_ReLU(5, 3),
    Centeredlayer(),
)

X = torch.randn((2, 5))
net(X)

tensor([[ 2.0080, -1.6655, -0.5443],
        [-2.2597,  0.4417,  2.0197]])