In [1]:
import torch

In [2]:
x = torch.arange(24).reshape(2, 3, 4)
y = torch.arange(24).reshape(2, 4, 3)

In [3]:
x

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [4]:
y

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17],
         [18, 19, 20],
         [21, 22, 23]]])

In [6]:
z = torch.bmm(x, y)

In [7]:
z

tensor([[[  42,   48,   54],
         [ 114,  136,  158],
         [ 186,  224,  262]],

        [[ 906,  960, 1014],
         [1170, 1240, 1310],
         [1434, 1520, 1606]]])

In [8]:
z.shape

torch.Size([2, 3, 3])

In [10]:
(x@y).shape

torch.Size([2, 3, 3])