In [13]:
import torch

In [14]:
X = torch.arange(30).reshape(2, 3, 5)
X

tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14]],

        [[15, 16, 17, 18, 19],
         [20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]]])

In [15]:
X.permute(1 ,0, 2)

tensor([[[ 0,  1,  2,  3,  4],
         [15, 16, 17, 18, 19]],

        [[ 5,  6,  7,  8,  9],
         [20, 21, 22, 23, 24]],

        [[10, 11, 12, 13, 14],
         [25, 26, 27, 28, 29]]])

In [16]:
X.transpose(1, 0)

tensor([[[ 0,  1,  2,  3,  4],
         [15, 16, 17, 18, 19]],

        [[ 5,  6,  7,  8,  9],
         [20, 21, 22, 23, 24]],

        [[10, 11, 12, 13, 14],
         [25, 26, 27, 28, 29]]])

In [17]:
X.transpose_(1, 0)

tensor([[[ 0,  1,  2,  3,  4],
         [15, 16, 17, 18, 19]],

        [[ 5,  6,  7,  8,  9],
         [20, 21, 22, 23, 24]],

        [[10, 11, 12, 13, 14],
         [25, 26, 27, 28, 29]]])