# 数据操作实现

In [1]:
import torch

In [6]:
# arange
x = torch.arange(15)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [7]:
x.size()

torch.Size([15])

In [8]:
x.shape

torch.Size([15])

In [9]:
x.numel()

15

In [11]:
# 改变形状
x.reshape(-1, 5)

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [14]:
# 创建zeros矩阵
zeros = torch.zeros((3, 4))

In [16]:
torch.ones_like(zeros)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [17]:
# 高斯分布矩阵
torch.randn(3, 4)

tensor([[ 0.4512,  0.3941,  0.0685, -0.9907],
        [-0.2062, -0.2266,  1.2411, -1.9985],
        [-0.9450,  0.5208,  0.7299, -0.6532]])

In [22]:
x = torch.arange(-10, 10, 2)
y = torch.sin(x)
x, y

(tensor([-10,  -8,  -6,  -4,  -2,   0,   2,   4,   6,   8]),
 tensor([ 0.5440, -0.9894,  0.2794,  0.7568, -0.9093,  0.0000,  0.9093, -0.7568,
         -0.2794,  0.9894]))

In [23]:
# 逻辑运算符构建二元张量
X = torch.Tensor([1, 2, 0, 1])
Y = torch.Tensor([1, 1, 0, -1])
X == Y

tensor([ True, False,  True, False])

### 节省内存

> 运行一些操作可能导致为新结果分配内存。例如, 如果我们用 Y = X + Y, 我们将取消引用Y指向的张量, 而是指向新分配的内存处的张量。

In [15]:
X = x
Y = X **2 
before = id(Y)
Y = Y + X
id(Y) == before

False

In [16]:
print(id(Y), id(X), before)

140481049058480 140481059738048 140481059888544


> 这样是可不取的, 原因有两个:
> 1. 首先, 我们不想总是不必要地分配内存。在机器学习中, 我们可能有数百兆的参数, 并且在一秒内多次更新所有参数。通常情况下, 我们希望原地执行这些操作。
> 2. 如果不原地更新, 其它引用仍然会指向旧的内存位置, 这样我们的代码可能会无意中引用旧的参数


In [17]:
Z = torch.zeros_like(Y)
print(f"id(Z) : {id(Z)}")
Z[:] = X + Y
print(f"id(Z) : {id(Z)}")

id(Z) : 140481047375968
id(Z) : 140481047375968


### 转换为其它的Python对象

In [18]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

# QA

In [33]:
a = torch.arange(12)
b = a.reshape((3,4))
b[:] = 2
a

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [30]:
import numpy as np
a = np.arange(12)
b = a.reshape(3, 4).copy()
b[0,0] = 2
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [27]:
id(a), id(b)

(140045766707504, 140045766707312)